export { default as LangSwitch } from './LangSwitch'
export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as ThemeSwitch } from './ThemeSwitch'
export { default as CTA } from './CTA'
export { default as Hero } from './Hero'
export { default as ScrollToTop } from './ScrollToTop'
